# Generated by scripts/generate_sync.py from tests/unit/test_keyvault_client.py.
# Do not edit; change the asynchronous original and run the generator.
"""Unit tests for the Key Vault wrapper, with the Azure SDK clients replaced by fakes."""

from __future__ import annotations

from types import SimpleNamespace
from typing import Any

import pytest

from azure_auth import AuthContext
from azure_auth._sync.keyvault import KeyVaultClient
from tests.fakes import FakeMsal

pytestmark = pytest.mark.unit

VAULT = "https://contoso.vault.azure.net"


class FakeSdkClient:
    """Stands in for SecretClient, CertificateClient and CryptographyClient."""

    created: list[FakeSdkClient]

    def __init__(self, target: str, credential: Any) -> None:
        self.target = target
        self.credential = credential
        self.calls: list[tuple[Any, ...]] = []
        self.closed = False
        FakeSdkClient.created.append(self)

    def get_secret(self, name: str, version: str | None) -> Any:
        self.calls.append(("get_secret", name, version))
        return SimpleNamespace(value=None if name == "empty" else f"value-of-{name}")

    def get_certificate(self, name: str) -> Any:
        self.calls.append(("get_certificate", name))
        return SimpleNamespace(cer=None if name == "empty" else bytearray(b"latest"))

    def get_certificate_version(self, name: str, version: str) -> Any:
        self.calls.append(("get_certificate_version", name, version))
        return SimpleNamespace(cer=bytearray(b"pinned"))

    def sign(self, algorithm: Any, digest: bytes) -> Any:
        self.calls.append(("sign", algorithm.value, digest))
        return SimpleNamespace(signature=bytearray(b"signature"))

    def verify(self, algorithm: Any, digest: bytes, signature: bytes) -> Any:
        self.calls.append(("verify", algorithm.value, digest, signature))
        return SimpleNamespace(is_valid=signature == b"signature")

    def close(self) -> None:
        self.closed = True


@pytest.fixture
def vault(monkeypatch: pytest.MonkeyPatch, fake_msal: FakeMsal) -> KeyVaultClient:
    FakeSdkClient.created = []
    for name in ("SecretClient", "CertificateClient", "CryptographyClient"):
        monkeypatch.setattr(f"azure_auth._sync.keyvault.{name}", FakeSdkClient)
    return KeyVaultClient(AuthContext("tenant", username="admin@contoso.com"), f"{VAULT}/")


def test_sdk_clients_get_the_vault_and_the_async_credential(vault: KeyVaultClient) -> None:
    secrets, certificates = FakeSdkClient.created
    assert vault.vault_url == secrets.target == certificates.target == VAULT
    assert secrets.credential is certificates.credential
    # The async wrapper hands over ``auth``; the generated blocking one hands over ``auth``.
    assert getattr(secrets.credential, "sync", secrets.credential).tenant_id == "tenant"


def test_get_secret(vault: KeyVaultClient) -> None:
    assert vault.get_secret("db-password") == "value-of-db-password"
    assert vault.get_secret("db-password", "v2") == "value-of-db-password"
    assert FakeSdkClient.created[0].calls == [
        ("get_secret", "db-password", None),
        ("get_secret", "db-password", "v2"),
    ]
    with pytest.raises(ValueError, match="has no value"):
        vault.get_secret("empty")


def test_get_certificate(vault: KeyVaultClient) -> None:
    assert vault.get_certificate("signing") == b"latest"
    assert vault.get_certificate("signing", "v1") == b"pinned"
    with pytest.raises(ValueError, match="has no content"):
        vault.get_certificate("empty")


def test_sign_and_verify_use_one_client_per_key(vault: KeyVaultClient) -> None:
    signature = vault.sign("signing", "PS256", b"digest")
    assert signature == b"signature"
    assert vault.verify("signing", "PS256", b"digest", signature) is True
    assert vault.verify("signing", "RS256", b"digest", b"forged", version="v1") is False

    crypto = FakeSdkClient.created[2:]
    assert [client.target for client in crypto] == [
        f"{VAULT}/keys/signing",
        f"{VAULT}/keys/signing/v1",
    ]
    assert crypto[0].calls == [
        ("sign", "PS256", b"digest"),
        ("verify", "PS256", b"digest", b"signature"),
    ]


def test_closing_closes_every_sdk_client(vault: KeyVaultClient) -> None:
    with vault:
        vault.sign("signing", "RS256", b"digest")
    assert [client.closed for client in FakeSdkClient.created] == [True, True, True]
