# Generated by scripts/generate_sync.py from src/azure_auth/clients/__init__.py.
# Do not edit; change the asynchronous original and run the generator.
"""Thin synchronous clients, one per resource.

``KeyVaultClient`` lives in :mod:`azure_auth._sync.keyvault` and is not imported here,
because it needs the optional ``keyvault`` extra.
"""

from __future__ import annotations

from azure_auth._sync.arm import AzureClient
from azure_auth._sync.base import ResourceClient
from azure_auth._sync.exchange import ExchangeClient
from azure_auth._sync.graph import GraphClient
from azure_auth._sync.invoke_command import InvokeCommandClient
from azure_auth._sync.ipps import IppsClient
from azure_auth.clients.errors import AzureError, GraphError, InvokeCommandError, ResourceError

__all__ = [
    "AzureClient",
    "AzureError",
    "ExchangeClient",
    "GraphClient",
    "GraphError",
    "InvokeCommandClient",
    "InvokeCommandError",
    "IppsClient",
    "ResourceClient",
    "ResourceError",
]
