# Generated by scripts/generate_sync.py from src/azure_auth/clients/arm.py.
# Do not edit; change the asynchronous client and run the generator.
"""Thin client for Azure Resource Manager.

For the typed management SDKs (``azure-mgmt-*``) no client is needed: pass the
:class:`~azure_auth.AuthContext` (or its ``aio`` view) as ``credential=``.
"""

from __future__ import annotations

import time
from collections.abc import Iterator, Mapping, Sequence
from typing import Any, ClassVar

import httpx

from azure_auth._sync.base import ResourceClient, retry_delay
from azure_auth.auth.context import AuthContext
from azure_auth.clients.errors import AzureError, ResourceError
from azure_auth.constants import ARM_RESOURCE, AZURE_POWERSHELL_CLIENT_ID

_TERMINAL_FAILURES = frozenset({"failed", "canceled", "cancelled"})
_DEFAULT_POLL_SECONDS = 5.0


class AzureClient(ResourceClient):
    """Authenticated requests to Azure Resource Manager.

    Every call needs the ``api_version`` of the resource provider being addressed.

    Example:
        >>> arm = AzureClient(auth)  # doctest: +SKIP
        >>> subs = arm.get_all("/subscriptions", api_version="2022-12-01")  # doctest: +SKIP
    """

    DEFAULT_CLIENT_ID: ClassVar[str] = AZURE_POWERSHELL_CLIENT_ID
    RESOURCE: ClassVar[str] = ARM_RESOURCE
    ERROR_CLASS: ClassVar[type[ResourceError]] = AzureError

    def __init__(
        self,
        auth: AuthContext,
        *,
        client_id: str | None = None,
        scopes: Sequence[str] | None = None,
        timeout: float = 100.0,
        max_retries: int = 3,
        max_retry_wait: float = 120.0,
        transport: httpx.BaseTransport | None = None,
    ) -> None:
        """Create the client. No network call is made.

        Args:
            auth: The authentication context to get tokens from.
            client_id: Client id for this client; see :class:`ResourceClient`.
            scopes: Scopes to request. Defaults to ``https://management.azure.com/.default``.
            timeout: Timeout for each HTTP request, in seconds.
            max_retries: How often a throttled request is retried.
            max_retry_wait: Longest wait before one retry, in seconds.
            transport: Custom ``httpx`` transport, mainly for tests.
        """
        super().__init__(
            auth,
            base_url=ARM_RESOURCE,
            client_id=client_id,
            scopes=scopes,
            timeout=timeout,
            max_retries=max_retries,
            max_retry_wait=max_retry_wait,
            transport=transport,
        )

    def send(
        self,
        method: str,
        path: str,
        *,
        api_version: str,
        params: Mapping[str, Any] | None = None,
        json: Any = None,
        headers: Mapping[str, str] | None = None,
    ) -> httpx.Response:
        """Send a request with its ``api-version`` and return the raw response.

        Use this when the response headers matter, for example to pass the response of a
        long-running operation to :meth:`wait`.

        Args:
            method: HTTP method.
            path: Resource path such as ``/subscriptions/{id}/resourceGroups/{name}``.
            api_version: API version of the resource provider.
            params: Further query parameters.
            json: Request body.
            headers: Extra request headers.

        Returns:
            The successful response.
        """
        query = {**(params or {}), "api-version": api_version}
        return self.request(method, path, params=query, json=json, headers=headers)

    def get(self, path: str, *, api_version: str, params: Mapping[str, Any] | None = None) -> Any:
        """Send a GET request.

        Args:
            path: Resource path.
            api_version: API version of the resource provider.
            params: Further query parameters.

        Returns:
            The parsed JSON body.
        """
        return self._json(self.send("GET", path, api_version=api_version, params=params))

    def put(self, path: str, json: Any = None, *, api_version: str) -> Any:
        """Send a PUT request. For long-running operations use :meth:`send` and :meth:`wait`.

        Args:
            path: Resource path.
            json: Request body.
            api_version: API version of the resource provider.

        Returns:
            The parsed JSON body, or ``None`` when the response has none.
        """
        return self._json(self.send("PUT", path, api_version=api_version, json=json))

    def post(self, path: str, json: Any = None, *, api_version: str) -> Any:
        """Send a POST request. For long-running operations use :meth:`send` and :meth:`wait`.

        Args:
            path: Resource or action path.
            json: Request body.
            api_version: API version of the resource provider.

        Returns:
            The parsed JSON body, or ``None`` when the response has none.
        """
        return self._json(self.send("POST", path, api_version=api_version, json=json))

    def patch(self, path: str, json: Any = None, *, api_version: str) -> Any:
        """Send a PATCH request.

        Args:
            path: Resource path.
            json: Request body.
            api_version: API version of the resource provider.

        Returns:
            The parsed JSON body, or ``None`` when the response has none.
        """
        return self._json(self.send("PATCH", path, api_version=api_version, json=json))

    def delete(self, path: str, *, api_version: str) -> Any:
        """Send a DELETE request. For long-running deletes use :meth:`send` and :meth:`wait`.

        Args:
            path: Resource path.
            api_version: API version of the resource provider.

        Returns:
            The parsed JSON body, or ``None`` when the response has none.
        """
        return self._json(self.send("DELETE", path, api_version=api_version))

    def iter_pages(
        self, path: str, *, api_version: str, params: Mapping[str, Any] | None = None
    ) -> Iterator[dict[str, Any]]:
        """Yield every page of a list operation, following ``nextLink``.

        Args:
            path: Path of the list operation.
            api_version: API version of the resource provider.
            params: Further query parameters for the first page.

        Yields:
            Each page as returned by Azure Resource Manager.
        """
        page = self.get(path, api_version=api_version, params=params)
        yield page
        while page.get("nextLink"):
            # A next link already carries api-version and every other parameter.
            page = self._json(self.request("GET", page["nextLink"]))
            yield page

    def get_all(
        self, path: str, *, api_version: str, params: Mapping[str, Any] | None = None
    ) -> list[Any]:
        """Return every item of a list operation, following ``nextLink``.

        Args:
            path: Path of the list operation.
            api_version: API version of the resource provider.
            params: Further query parameters for the first page.

        Returns:
            The items of all pages, in order.
        """
        items: list[Any] = []
        for page in self.iter_pages(path, api_version=api_version, params=params):
            items.extend(page.get("value", []))
        return items

    def wait(
        self,
        response: httpx.Response,
        *,
        timeout: float = 1800.0,
        poll_interval: float | None = None,
    ) -> Any:
        """Wait for the long-running operation started by ``response`` to finish.

        Polls the ``Azure-AsyncOperation`` URL when the response has one, else the
        ``Location`` URL, waiting ``Retry-After`` seconds between polls.

        Args:
            response: The response of :meth:`send` that started the operation.
            timeout: Give up after this many seconds.
            poll_interval: Seconds between polls; overrides ``Retry-After``.

        Returns:
            The final resource for PUT and PATCH, the ``Location`` result when there is one,
            else the final operation status. When the operation had already completed, the
            body of ``response``.

        Raises:
            AzureError: If the operation fails or is cancelled.
            TimeoutError: If the operation does not finish in time.
        """
        deadline = time.monotonic() + timeout
        operation_url = response.headers.get("Azure-AsyncOperation")
        location_url = response.headers.get("Location")

        def delay(latest: httpx.Response) -> float:
            if poll_interval is not None:
                return poll_interval
            if "Retry-After" in latest.headers:
                return retry_delay(latest, 1, self._max_retry_wait)
            return _DEFAULT_POLL_SECONDS

        if operation_url:
            latest = response
            while True:
                if time.monotonic() > deadline:
                    raise TimeoutError(f"Operation still running after {timeout} s")
                time.sleep(delay(latest))
                latest = self.request("GET", operation_url)
                status = self._json(latest) or {}
                state = str(status.get("status", "")).lower()
                if state in _TERMINAL_FAILURES:
                    raise self._operation_error(latest, status)
                if state == "succeeded":
                    break
            if response.request.method in {"PUT", "PATCH"}:
                return self._json(self.request("GET", str(response.request.url)))
            if location_url:
                return self._json(self.request("GET", location_url))
            return status

        if response.status_code == httpx.codes.ACCEPTED and location_url:
            latest = response
            while latest.status_code == httpx.codes.ACCEPTED:
                if time.monotonic() > deadline:
                    raise TimeoutError(f"Operation still running after {timeout} s")
                time.sleep(delay(latest))
                latest = self.request("GET", location_url)
            return self._json(latest)

        return self._json(response)

    def _operation_error(self, response: httpx.Response, status: Mapping[str, Any]) -> AzureError:
        """Build the exception for a failed long-running operation.

        Args:
            response: The poll response that reported the failure.
            status: The operation status body.

        Returns:
            The exception to raise.
        """
        error = status.get("error") or {}
        code = error.get("code") if isinstance(error, dict) else None
        message = error.get("message") if isinstance(error, dict) else None
        detail = ": ".join(str(part) for part in (code, message) if part)
        return AzureError(
            f"Operation {status.get('status')} {detail}".rstrip(),
            status=response.status_code,
            code=str(code) if code else None,
            request_id=response.headers.get("x-ms-request-id"),
            body=dict(status),
        )
