# Generated by scripts/generate_sync.py from src/azure_auth/clients/exchange.py.
# Do not edit; change the asynchronous original and run the generator.
"""Client for Exchange Online cmdlets."""

from __future__ import annotations

from urllib.parse import urlsplit

from azure_auth._sync.invoke_command import InvokeCommandClient
from azure_auth.clouds import Cloud


class ExchangeClient(InvokeCommandClient):
    """Run Exchange Online cmdlets without PowerShell.

    User flows default to the Exchange Online PowerShell client id, which is pre-authorised
    for Exchange. App flows need the ``Exchange.ManageAsApp`` application permission and an
    Exchange administrator role assigned to the service principal.

    Example:
        >>> exchange = ExchangeClient(auth)  # doctest: +SKIP
        >>> mailboxes = exchange.run("Get-Mailbox")  # doctest: +SKIP

    Note:
        ``ResultSize`` is not a cmdlet parameter on this endpoint. The PowerShell module
        applies it client side while consuming pages, so ``InvokeCommand`` ignores it and
        ``run`` returns every result. Use :meth:`~InvokeCommandClient.iter_pages` and stop
        when you have enough.
    """

    @classmethod
    def service(cls, cloud: Cloud) -> tuple[str, str]:
        """Name Exchange Online in a cloud.

        Args:
            cloud: The cloud.

        Returns:
            The resource, and its host, which is where requests go.
        """
        return cloud.exchange, urlsplit(cloud.exchange).hostname or ""
