# Generated by scripts/generate_sync.py from src/azure_auth/clients/invoke_command.py.
# Do not edit; change the asynchronous original and run the generator.
"""Cmdlet invocation over the Exchange admin REST API.

Exchange Online and Security & Compliance PowerShell both talk to an undocumented REST
endpoint, ``/adminapi/<version>/<tenant id>/InvokeCommand``. The request shape used here was
read from the ExchangeOnlineManagement module (3.10.1). Because the endpoint is
undocumented, everything that knows about it lives in this module.
"""

from __future__ import annotations

import base64
import binascii
import json as json_module
import uuid
from collections.abc import Iterator, Sequence
from typing import Any, ClassVar, Literal

import httpx

from azure_auth._sync.base import ResourceClient
from azure_auth.auth.context import AuthContext
from azure_auth.clients.errors import InvokeCommandError, ResourceError
from azure_auth.constants import EXCHANGE_POWERSHELL_CLIENT_ID

# The arbitration mailbox Exchange uses to route requests that are not made by a mailbox
# user of the tenant: app-only access and delegated (GDAP) access.
SYSTEM_MAILBOX = "SystemMailbox{bb558c35-97f1-4cb9-8ff7-d53741dc928c}"


def tenant_id_from_token(token: str) -> str | None:
    """Read the ``tid`` claim of an access token, without validating the token.

    Args:
        token: A JWT access token.

    Returns:
        The tenant id (GUID), or ``None`` when the token cannot be decoded.
    """
    parts = token.split(".")
    if len(parts) < 2:  # a JWT is header.payload[.signature]
        return None
    try:
        payload = json_module.loads(base64.urlsafe_b64decode(parts[1] + "=" * (-len(parts[1]) % 4)))
    except binascii.Error, ValueError:
        return None
    tenant = payload.get("tid") if isinstance(payload, dict) else None
    return str(tenant) if tenant else None


class InvokeCommandClient(ResourceClient):
    """Base class for clients that run cmdlets through ``InvokeCommand``.

    Attributes:
        HOST: Host name of the service.
        last_warnings: Warnings the service returned for the most recent cmdlet.
    """

    DEFAULT_CLIENT_ID: ClassVar[str] = EXCHANGE_POWERSHELL_CLIENT_ID
    ERROR_CLASS: ClassVar[type[ResourceError]] = InvokeCommandError
    HOST: ClassVar[str]

    def __init__(
        self,
        auth: AuthContext,
        *,
        client_id: str | None = None,
        scopes: Sequence[str] | None = None,
        anchor_mailbox: str | None = None,
        api_version: Literal["beta", "v1.0"] = "beta",
        page_size: int = 1000,
        timeout: float = 300.0,
        max_retries: int = 3,
        max_retry_wait: float = 120.0,
        transport: httpx.BaseTransport | None = None,
    ) -> None:
        """Create the client. No network call is made.

        Args:
            auth: The authentication context to get tokens from.
            client_id: Client id for this client; see :class:`ResourceClient`.
            scopes: Scopes to request. Defaults to ``https://<host>/.default``.
            anchor_mailbox: Value of the ``X-AnchorMailbox`` routing header. Defaults to the
                signed-in user for a user flow in its own tenant, and to the tenant's system
                mailbox for app flows and for sibling (GDAP) contexts.
            api_version: ``beta`` (what the PowerShell module uses) or ``v1.0``.
            page_size: Preferred number of results per page.
            timeout: Timeout for each HTTP request, in seconds. Cmdlets can be slow.
            max_retries: How often a throttled request is retried.
            max_retry_wait: Longest wait before one retry, in seconds.
            transport: Custom ``httpx`` transport, mainly for tests.
        """
        super().__init__(
            auth,
            base_url=f"https://{self.HOST}",
            client_id=client_id,
            scopes=scopes,
            timeout=timeout,
            max_retries=max_retries,
            max_retry_wait=max_retry_wait,
            transport=transport,
        )
        self._anchor_mailbox = anchor_mailbox
        self._api_version = api_version
        self._page_size = page_size
        self._connection_id = str(uuid.uuid4())
        self._tenant_guid: str | None = None
        self.last_warnings: list[str] = []

    def _is_trusted_host(self, host: str) -> bool:
        """Accept the service host and its regional sub-hosts.

        Args:
            host: Host name of the request URL.

        Returns:
            ``True`` for ``HOST`` and for ``<region>.HOST``.
        """
        lowered = host.lower()
        return lowered == self.HOST or lowered.endswith(f".{self.HOST}")

    def _tenant(self) -> str:
        """Return the tenant GUID for the request path.

        The service wants the GUID, and the context may have been given a domain name, so
        the GUID is read from the ``tid`` claim of the access token.

        Returns:
            The tenant GUID, or the context's tenant id when the token cannot be decoded.
        """
        if self._tenant_guid is None:
            token = self._tokens.acquire_token(self._scopes, client_id=self._client_id)
            self._tenant_guid = tenant_id_from_token(token.token) or self._auth.tenant_id
        return self._tenant_guid

    def _anchor(self, tenant: str) -> str:
        """Build the ``X-AnchorMailbox`` routing header.

        Args:
            tenant: Tenant GUID.

        Returns:
            The configured anchor, else the user's mailbox for a user flow in its own tenant,
            else the tenant's system mailbox.
        """
        if self._anchor_mailbox:
            return self._anchor_mailbox
        if self._auth.is_app_flow or self._auth.is_sibling:
            return f"APP:{SYSTEM_MAILBOX}@{tenant}"
        return f"UPN:{self._auth.username}"

    def _post(self, url: str, payload: dict[str, Any], cmdlet: str) -> httpx.Response:
        """Send one ``InvokeCommand`` request, following a regional redirect by hand.

        ``httpx`` drops the ``Authorization`` header when a redirect changes the host, and
        Security & Compliance answers the first call with a redirect to a regional host. So
        the redirect is read here, the regional host becomes the new base URL, and the
        request is sent again with its token.

        Args:
            url: Request URL or path.
            payload: The request body.
            cmdlet: Name of the cmdlet, for the diagnostic header.

        Returns:
            The successful response.
        """
        tenant = self._tenant()
        headers = {
            "Accept": "application/json",
            "Content-Type": "application/json;odata.metadata=minimal",
            "Prefer": f"odata.maxpagesize={self._page_size}",
            "X-AnchorMailbox": self._anchor(tenant),
            "X-CmdletName": cmdlet,
            "X-ResponseFormat": "json",
            "connection-id": self._connection_id,
            "client-request-id": str(uuid.uuid4()),
        }
        response = self.request("POST", url, json=payload, headers=headers)
        location = response.headers.get("Location")
        if response.status_code == httpx.codes.FOUND and location:
            region = httpx.URL(location).host.split(".", 1)[0]
            if region and not self._base_url.host.startswith(f"{region}."):
                self._base_url = httpx.URL(f"https://{region}.{self.HOST}/")
                target = httpx.URL(url) if "://" in url else None
                retry_url = str(target.copy_with(host=self._base_url.host)) if target else url
                response = self.request("POST", retry_url, json=payload, headers=headers)
        if response.is_redirect:
            # A redirect that could not be followed must not look like an empty result.
            raise self._error(response)
        return response

    def iter_pages(self, cmdlet: str, **parameters: Any) -> Iterator[dict[str, Any]]:
        """Run a cmdlet and yield each page of its output.

        Args:
            cmdlet: Cmdlet name such as ``Get-Mailbox``.
            **parameters: Cmdlet parameters. Use ``True`` for switch parameters.

        Yields:
            Each response page; the results are under ``value``.
        """
        payload = {"CmdletInput": {"CmdletName": cmdlet, "Parameters": parameters}}
        tenant = self._tenant()
        url: str | None = f"/adminapi/{self._api_version}/{tenant}/InvokeCommand"
        self.last_warnings = []
        while url:
            response = self._post(url, payload, cmdlet)
            warnings = response.headers.get("X-Warnings")
            if warnings:
                self.last_warnings.append(warnings)
            page = self._json(response) or {}
            yield page
            url = page.get("@odata.nextLink")

    def run(self, cmdlet: str, **parameters: Any) -> list[dict[str, Any]]:
        """Run a cmdlet and return all of its output.

        Args:
            cmdlet: Cmdlet name such as ``Get-Mailbox``.
            **parameters: Cmdlet parameters. Use ``True`` for switch parameters.

        Returns:
            The output objects as dictionaries.

        Raises:
            InvokeCommandError: If the service rejects the cmdlet.
        """
        results: list[dict[str, Any]] = []
        for page in self.iter_pages(cmdlet, **parameters):
            results.extend(page.get("value", []))
        return results
