# Generated by scripts/generate_sync.py from src/azure_auth/clients/keyvault.py.
# Do not edit; change the asynchronous original and run the generator.
"""Thin wrapper over the Azure Key Vault SDK clients.

The Azure SDK does the work; this wrapper only wires an :class:`~azure_auth.AuthContext` into
it and exposes the handful of calls that authentication code tends to need. For anything
else, use the SDK clients directly with ``credential=auth``.

Needs the ``keyvault`` extra: ``pip install azure-auth[keyvault]``.
"""

from __future__ import annotations

from types import TracebackType
from typing import Self

from azure_auth.auth.context import AuthContext

try:
    from azure.keyvault.certificates import CertificateClient
    from azure.keyvault.keys.crypto import CryptographyClient, SignatureAlgorithm
    from azure.keyvault.secrets import SecretClient
except ImportError as exc:  # pragma: no cover (exercised only without the extra)
    raise ImportError(
        "KeyVaultClient needs the 'keyvault' extra: pip install azure-auth[keyvault]"
    ) from exc


class KeyVaultClient:
    """Secrets, certificates and signing keys of one vault.

    Example:
        >>> vault = KeyVaultClient(auth, "https://contoso.vault.azure.net")  # doctest: +SKIP
        >>> password = vault.get_secret("service-password")  # doctest: +SKIP
    """

    def __init__(self, auth: AuthContext, vault_url: str) -> None:
        """Create the client. No network call is made.

        Args:
            auth: The authentication context to get tokens from. User flows use the Azure
                PowerShell client id unless the context names another.
            vault_url: URL of the vault, such as ``https://contoso.vault.azure.net``.
        """
        self._vault_url = vault_url.rstrip("/")
        self._credential = auth
        self._secrets = SecretClient(self._vault_url, self._credential)
        self._certificates = CertificateClient(self._vault_url, self._credential)
        self._crypto: dict[str, CryptographyClient] = {}

    @property
    def vault_url(self) -> str:
        """URL of the vault."""
        return self._vault_url

    def get_secret(self, name: str, version: str | None = None) -> str:
        """Read a secret value.

        Args:
            name: Name of the secret.
            version: Version to read. Defaults to the latest.

        Returns:
            The secret value.

        Raises:
            ValueError: If the secret has no value.
        """
        secret = self._secrets.get_secret(name, version)
        if secret.value is None:
            raise ValueError(f"Secret {name!r} has no value")
        return secret.value

    def get_certificate(self, name: str, version: str | None = None) -> bytes:
        """Read the public part of a certificate.

        Args:
            name: Name of the certificate.
            version: Version to read. Defaults to the latest.

        Returns:
            The DER-encoded certificate, without its private key.

        Raises:
            ValueError: If the certificate has no content.
        """
        if version:
            certificate = self._certificates.get_certificate_version(name, version)
        else:
            certificate = self._certificates.get_certificate(name)
        if certificate.cer is None:
            raise ValueError(f"Certificate {name!r} has no content")
        return bytes(certificate.cer)

    def _crypto_client(self, key_name: str, version: str | None) -> CryptographyClient:
        """Return the cryptography client for one key.

        Args:
            key_name: Name of the key.
            version: Key version, or ``None`` for the latest.

        Returns:
            A memoised ``CryptographyClient``.
        """
        key_id = f"{self._vault_url}/keys/{key_name}" + (f"/{version}" if version else "")
        if key_id not in self._crypto:
            self._crypto[key_id] = CryptographyClient(key_id, self._credential)
        return self._crypto[key_id]

    def sign(
        self,
        key_name: str,
        algorithm: SignatureAlgorithm | str,
        digest: bytes,
        *,
        version: str | None = None,
    ) -> bytes:
        """Sign a digest with a key that stays in the vault.

        Args:
            key_name: Name of the key.
            algorithm: Signature algorithm, such as ``PS256`` or ``RS256``.
            digest: The digest to sign, hashed to match ``algorithm``.
            version: Key version. Defaults to the latest.

        Returns:
            The signature.
        """
        client = self._crypto_client(key_name, version)
        result = client.sign(SignatureAlgorithm(algorithm), digest)
        return bytes(result.signature)

    def verify(
        self,
        key_name: str,
        algorithm: SignatureAlgorithm | str,
        digest: bytes,
        signature: bytes,
        *,
        version: str | None = None,
    ) -> bool:
        """Verify a signature with a key in the vault.

        Args:
            key_name: Name of the key.
            algorithm: Signature algorithm, such as ``PS256`` or ``RS256``.
            digest: The digest that was signed.
            signature: The signature to check.
            version: Key version. Defaults to the latest.

        Returns:
            Whether the signature is valid.
        """
        client = self._crypto_client(key_name, version)
        result = client.verify(SignatureAlgorithm(algorithm), digest, signature)
        return bool(result.is_valid)

    def close(self) -> None:
        """Close the underlying SDK clients."""
        self._secrets.close()
        self._certificates.close()
        for client in self._crypto.values():
            client.close()

    def __enter__(self) -> Self:
        """Enter the context manager.

        Returns:
            This client.
        """
        return self

    def __exit__(
        self,
        exc_type: type[BaseException] | None = None,
        exc_value: BaseException | None = None,
        traceback: TracebackType | None = None,
    ) -> None:
        """Close the client when leaving the context manager."""
        self.close()
