"""Generate the synchronous clients in ``azure_auth._sync`` from ``azure_auth.clients``.

The asynchronous clients are the source of truth. This script rewrites them into blocking
code with a fixed list of textual substitutions (the approach the ``unasync`` project uses),
then lets ruff sort imports and format the result, so the output is deterministic.

The unit tests of the asynchronous clients are mirrored the same way, into
``tests/unit/sync``, so the blocking clients are held to exactly the same behaviour.

Usage::

    uv run python scripts/generate_sync.py          # rewrite the mirrors
    uv run python scripts/generate_sync.py --check  # exit 1 if a mirror is out of date

Generated files are committed. ``tests/integration/test_sync_mirror.py`` runs the check, so
an edit to an asynchronous client or test that is not mirrored fails the test suite.
"""

from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PACKAGE = ROOT / "src" / "azure_auth"

# ``clients/errors.py`` has no asynchronous code and is shared, so it is not mirrored.
_CLIENT_MODULES = ("base", "graph", "arm", "invoke_command", "exchange", "ipps", "keyvault")
_MIRRORED = "|".join(_CLIENT_MODULES)


@dataclass(frozen=True)
class Mirror:
    """One directory of generated modules.

    Attributes:
        source: Directory holding the asynchronous originals.
        target: Directory the blocking versions are written to.
        modules: Names of the mirrored modules, without extension.
        package_docstring: Docstring for a generated ``__init__.py``, or ``None`` when
            ``__init__`` is itself one of ``modules``.
    """

    source: Path
    target: Path
    modules: tuple[str, ...]
    package_docstring: str | None = None


MIRRORS = (
    Mirror(PACKAGE / "clients", PACKAGE / "_sync", ("__init__", *_CLIENT_MODULES)),
    Mirror(
        ROOT / "tests" / "unit",
        ROOT / "tests" / "unit" / "sync",
        ("test_graph_client", "test_arm_client", "test_invoke_command", "test_keyvault_client"),
        package_docstring="Generated tests for the blocking clients.",
    ),
)

HEADER = (
    "# Generated by scripts/generate_sync.py from {source}.\n"
    "# Do not edit; change the asynchronous original and run the generator.\n"
)

SUBSTITUTIONS: tuple[tuple[re.Pattern[str], str], ...] = tuple(
    (re.compile(pattern, re.MULTILINE), replacement)
    for pattern, replacement in (
        # imports and dotted names
        (rf"azure_auth\.clients\.({_MIRRORED})\b", r"azure_auth._sync.\1"),
        (r"from azure_auth\.clients import", "from azure_auth._sync import"),
        (r"(azure\.keyvault\.[\w.]+?)\.aio\b", r"\1"),
        (r"^import asyncio$", "import time"),
        # tests
        (
            r"pytestmark = \[pytest\.mark\.unit, pytest\.mark\.anyio\]",
            "pytestmark = pytest.mark.unit",
        ),
        # syntax
        (r"\basync (def|with|for)\b", r"\1"),
        (r"\bawait ", ""),
        # names
        (r"\bauth\.aio\b", "auth"),
        (r"\basyncio\.sleep\b", "time.sleep"),
        (r"\bAsyncClient\b", "Client"),
        (r"\bAsyncBaseTransport\b", "BaseTransport"),
        (r"\bAsyncIterator\b", "Iterator"),
        (r"\baclose\b", "close"),
        (r"__aenter__", "__enter__"),
        (r"__aexit__", "__exit__"),
        # prose
        (r"\basynchronous\b", "synchronous"),
        (r"\bThin async clients\b", "Thin blocking clients"),
    )
)


def transform(origin: str, source: str) -> str:
    """Rewrite one asynchronous module into its synchronous mirror.

    Args:
        origin: Path of the original, relative to the repository, for the generated header.
        source: Source code of the asynchronous module.

    Returns:
        Source code of the synchronous module, before import sorting and formatting.
    """
    for pattern, replacement in SUBSTITUTIONS:
        source = pattern.sub(replacement, source)

    # ``import asyncio`` became ``import time``; drop it when the module had one already.
    seen_time = False
    kept: list[str] = []
    for line in source.splitlines(keepends=True):
        if line.strip() == "import time":
            if seen_time:
                continue
            seen_time = True
        kept.append(line)
    return HEADER.format(source=origin) + "".join(kept)


def generate(mirror: Mirror, target: Path) -> None:
    """Write one mirror into ``target`` and normalise it with ruff.

    Args:
        mirror: What to generate.
        target: Directory to write to. It is emptied first.
    """
    if target.exists():
        shutil.rmtree(target)
    target.mkdir(parents=True)
    if mirror.package_docstring is not None:
        (target / "__init__.py").write_text(
            f'"""{mirror.package_docstring}"""\n', encoding="utf-8", newline="\n"
        )
    for name in mirror.modules:
        original = mirror.source / f"{name}.py"
        origin = original.relative_to(ROOT).as_posix()
        text = transform(origin, original.read_text(encoding="utf-8"))
        (target / f"{name}.py").write_text(text, encoding="utf-8", newline="\n")

    config = str(ROOT / "pyproject.toml")
    for command in (
        ["check", "--quiet", "--select", "I", "--fix", "--config", config],
        ["format", "--quiet", "--config", config],
    ):
        subprocess.run(  # noqa: S603 (fixed argv list, no shell)
            [sys.executable, "-m", "ruff", *command, str(target)], check=True, cwd=ROOT
        )


def differences(expected: Path, actual: Path) -> list[str]:
    """Compare a freshly generated directory with the one that is checked in.

    Args:
        expected: Freshly generated mirror.
        actual: Mirror that is checked in.

    Returns:
        One message per file that is missing, unexpected or different.
    """
    label = actual.relative_to(ROOT).as_posix()
    fresh = {path.name: path for path in expected.glob("*.py")}
    current = {path.name: path for path in actual.glob("*.py")} if actual.exists() else {}
    problems = [f"missing: {label}/{name}" for name in sorted(fresh.keys() - current.keys())]
    problems += [f"unexpected: {label}/{name}" for name in sorted(current.keys() - fresh.keys())]
    for name in sorted(fresh.keys() & current.keys()):
        checked_in = current[name].read_text(encoding="utf-8").replace("\r\n", "\n")
        if fresh[name].read_text(encoding="utf-8") != checked_in:
            problems.append(f"out of date: {label}/{name}")
    return problems


def main(argv: list[str] | None = None) -> int:
    """Generate the mirrors, or check that the checked-in mirrors are current.

    Args:
        argv: Command line arguments; defaults to ``sys.argv[1:]``.

    Returns:
        Process exit code: 0 on success, 1 when ``--check`` finds a stale mirror.
    """
    parser = argparse.ArgumentParser(description=(__doc__ or "").splitlines()[0])
    parser.add_argument("--check", action="store_true", help="verify instead of writing")
    arguments = parser.parse_args(argv)

    if not arguments.check:
        for mirror in MIRRORS:
            generate(mirror, mirror.target)
            count = len(mirror.modules)
            print(f"Generated {count} modules in {mirror.target.relative_to(ROOT).as_posix()}")
        return 0

    problems: list[str] = []
    for mirror in MIRRORS:
        # Generate next to the real mirror so ruff classifies imports the same way.
        scratch = Path(tempfile.mkdtemp(prefix="_sync_check_", dir=mirror.target.parent))
        try:
            generate(mirror, scratch)
            problems += differences(scratch, mirror.target)
        finally:
            shutil.rmtree(scratch, ignore_errors=True)
    for problem in problems:
        print(problem)
    if problems:
        print("Run: uv run python scripts/generate_sync.py")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
