"""Generate the synchronous clients in ``azure_auth._sync`` from ``azure_auth.clients``.

The asynchronous clients are the source of truth. This script rewrites them into blocking
code with a fixed list of textual substitutions (the approach the ``unasync`` project uses),
then lets ruff sort imports and format the result, so the output is deterministic.

Usage::

    uv run python scripts/generate_sync.py          # rewrite src/azure_auth/_sync
    uv run python scripts/generate_sync.py --check  # exit 1 if the mirror is out of date

Generated files are committed. ``tests/integration/test_sync_mirror.py`` runs the check, so
an edit to an asynchronous client that is not mirrored fails the test suite.
"""

from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PACKAGE = ROOT / "src" / "azure_auth"
SOURCE = PACKAGE / "clients"
TARGET = PACKAGE / "_sync"

# Modules that are mirrored. ``errors.py`` has no asynchronous code and is shared.
MODULES = (
    "__init__",
    "base",
    "graph",
    "arm",
    "invoke_command",
    "exchange",
    "ipps",
    "keyvault",
)
_MIRRORED = "|".join(name for name in MODULES if name != "__init__")

HEADER = (
    "# Generated by scripts/generate_sync.py from src/azure_auth/clients/{name}.py.\n"
    "# Do not edit; change the asynchronous client and run the generator.\n"
)

SUBSTITUTIONS: tuple[tuple[re.Pattern[str], str], ...] = tuple(
    (re.compile(pattern, re.MULTILINE), replacement)
    for pattern, replacement in (
        # imports
        (rf"azure_auth\.clients\.({_MIRRORED})\b", r"azure_auth._sync.\1"),
        (r"from azure_auth\.clients import", "from azure_auth._sync import"),
        (r"(azure\.keyvault\.[\w.]+?)\.aio\b", r"\1"),
        (r"^import asyncio$", "import time"),
        # syntax
        (r"\basync (def|with|for)\b", r"\1"),
        (r"\bawait ", ""),
        # names
        (r"\bauth\.aio\b", "auth"),
        (r"\basyncio\.sleep\b", "time.sleep"),
        (r"\bAsyncClient\b", "Client"),
        (r"\bAsyncBaseTransport\b", "BaseTransport"),
        (r"\bAsyncIterator\b", "Iterator"),
        (r"\baclose\b", "close"),
        (r"__aenter__", "__enter__"),
        (r"__aexit__", "__exit__"),
        # prose
        (r"\basynchronous\b", "synchronous"),
        (r"\bThin async clients\b", "Thin blocking clients"),
    )
)


def transform(name: str, source: str) -> str:
    """Rewrite one asynchronous module into its synchronous mirror.

    Args:
        name: Module name without extension, used in the generated header.
        source: Source code of the asynchronous module.

    Returns:
        Source code of the synchronous module, before import sorting and formatting.
    """
    for pattern, replacement in SUBSTITUTIONS:
        source = pattern.sub(replacement, source)

    # ``import asyncio`` became ``import time``; drop it when the module had one already.
    lines = source.splitlines(keepends=True)
    seen_time = False
    kept: list[str] = []
    for line in lines:
        if line.strip() == "import time":
            if seen_time:
                continue
            seen_time = True
        kept.append(line)
    return HEADER.format(name=name) + "".join(kept)


def generate(target: Path) -> None:
    """Write the synchronous mirror into ``target`` and normalise it with ruff.

    Args:
        target: Directory to write to. It is emptied first.
    """
    if target.exists():
        shutil.rmtree(target)
    target.mkdir(parents=True)
    for name in MODULES:
        source = (SOURCE / f"{name}.py").read_text(encoding="utf-8")
        (target / f"{name}.py").write_text(transform(name, source), encoding="utf-8", newline="\n")

    config = str(ROOT / "pyproject.toml")
    for command in (
        ["check", "--quiet", "--select", "I", "--fix", "--config", config],
        ["format", "--quiet", "--config", config],
    ):
        subprocess.run(  # noqa: S603 (fixed argv list, no shell)
            [sys.executable, "-m", "ruff", *command, str(target)], check=True, cwd=ROOT
        )


def differences(expected: Path, actual: Path) -> list[str]:
    """Compare two generated directories.

    Args:
        expected: Freshly generated mirror.
        actual: Mirror that is checked in.

    Returns:
        One message per file that is missing, unexpected or different.
    """
    expected_files = {path.name: path for path in expected.glob("*.py")}
    actual_files = {path.name: path for path in actual.glob("*.py")} if actual.exists() else {}
    problems = [f"missing: {name}" for name in sorted(expected_files.keys() - actual_files.keys())]
    problems += [f"unexpected: {n}" for n in sorted(actual_files.keys() - expected_files.keys())]
    for name in sorted(expected_files.keys() & actual_files.keys()):
        fresh = expected_files[name].read_text(encoding="utf-8")
        current = actual_files[name].read_text(encoding="utf-8").replace("\r\n", "\n")
        if fresh != current:
            problems.append(f"out of date: {name}")
    return problems


def main(argv: list[str] | None = None) -> int:
    """Generate the mirror, or check that the checked-in mirror is current.

    Args:
        argv: Command line arguments; defaults to ``sys.argv[1:]``.

    Returns:
        Process exit code: 0 on success, 1 when ``--check`` finds a stale mirror.
    """
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="verify instead of writing")
    arguments = parser.parse_args(argv)

    if not arguments.check:
        generate(TARGET)
        print(f"Generated {len(MODULES)} modules in {TARGET.relative_to(ROOT)}")
        return 0

    # Generate next to the real mirror so ruff classifies imports the same way.
    scratch = Path(tempfile.mkdtemp(prefix="_sync_check_", dir=PACKAGE))
    try:
        generate(scratch)
        problems = differences(scratch, TARGET)
    finally:
        shutil.rmtree(scratch, ignore_errors=True)
    for problem in problems:
        print(problem)
    if problems:
        print("Run: uv run python scripts/generate_sync.py")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
